spring.application.name=turnlook

# base de datos
spring.datasource.url=jdbc:postgresql://host:port/bdd
spring.datasource.username=usuario
spring.datasource.password=contra

spring.datasource.driver-class-name=org.postgresql.Driver

# oauth
spring.security.oauth2.client.registration.github.client-id=YOUR_CLIENT_ID
spring.security.oauth2.client.registration.github.client-secret=YOUR_CLIENT_SECRET

spring.security.oauth2.client.registration.google.client-id=YOUR_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_CLIENT_SECRET

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



# ESTE ES PARA MYSQL

# base de datos
#spring.datasource.url=jdbc:mysql://172.16.1.64:3306/base_de_datos
#spring.datasource.username=bdd1
#spring.datasource.password=bdd1

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=validate     (o update)
#spring.jpa.show-sql=true