spring.application.name=turnlook

spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.fauqjajdjktmgymppscd
spring.datasource.password=cpms67__gg30

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

mercadopago.access-token=APP_USR-8394165203799126-060321-9fa153e909d496e55d793d8a195ba822-3449229460

jwt.secret=H7mP9xK2vR4tN8wQ1zY6cD3fG5hJ9sL2bV7uA4eR8iT1oP6